### ISSUE TITLE
[BUG] Number of citizens doesn't increase after researching Hamlet and Village

### ISSUE THREAD

**Issue by DmitryScaletta** [ldtteam/minecolonies#9015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1289-ALPHA

### Structurize Version

1.0.472-BETA

### Related Mods and their Versions

Modpack: [All the Mods 8](https://www.curseforge.com/minecraft/modpacks/all-the-mods-8)
It has `1.0.1247-BETA` version of MineColonies but I also tried the latest `1.0.1289-ALPHA` version and the issue is still exists.

<details>
  <summary>Modpack configs</summary>

**minecolonies-common.toml**

```toml
#All configuration items related to the core gameplay
[gameplay]
	#Whether to generate supply ships and camps in loot chests. [Default: true]
	generatesupplyloot = true

```

**minecolonies-client.toml**

```toml
#All configuration items related to the core gameplay
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment [Default: true]
	enablecitizenvoices = true
	#By default, when placing a schematic near other buildings, the already-placed buildings will show as if they were at level 5 and have a blue outline around them. You can disable that by setting this to false. [Default: true]
	neighborbuildingrendering = true
	#How close a building needs to be to another to be considered a neighbor, in blocks. -1 = intersecting, 0 = touching [Default: 4, min: -2, max: 16]
	#Range: -2 ~ 16
	neighborbuildingrange = 4
	#How close (in blocks) you need to be to see work orders while wearing the Build Goggles. [Default: 50, min: 1, max: 250]
	#Range: 1 ~ 250
	buildgogglerange = 50
	#When true, the colony borders shown when holding the build tool will be in the colony's team color. When false, the colony you're inside will be white and any other colony will be red. [Default: true]
	colonyteamborders = true
```

</details>

### Current Behavior

Number of citizens doesn't increase after researching Hamlet and Village

![image](https://user-images.githubusercontent.com/5096735/226088441-f0bd5ebc-9c6e-4684-8be2-d460a620e881.png)

![image](https://user-images.githubusercontent.com/5096735/226088454-67c459d9-74ad-476a-9263-81cda1574fe6.png)

### Expected Behavior

Number of citizens increase after researching Hamlet and Village

### Reproduction Steps

1. Build Town Hall level 3
1. Build University level 3
1. Research Hamlet

### Logs

-

### Anything else?

Similar Issue from the ATM discord

![image](https://user-images.githubusercontent.com/5096735/226088325-a131108f-c8ba-40f2-b1ab-71e6c77289f5.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
