### ISSUE TITLE
[BUG] Builder won't accept material from Domum Ornamentum Mod

### ISSUE THREAD

**Issue by SCBionicle** [ldtteam/minecolonies#9661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.385-BETA

### Structurize Version

1.20.1-1.0.674-BETA

### Related Mods and their Versions

All mods in used mod pack can be seen in this modpack repo: https://github.com/SCBionicle/MinecoloniesLT/commit/1f7eb815b39faa4541d6feeb57e8e64c4346747a (please view from this snapshot, a mod rollback is being performed so that players can continue to play)

domum_ornamentum-1.20.1-1.0.148-BETA-universal

### Current Behavior

Builders will constantly ask for Domum Ornamentum panels of the vertical variety. They will not accept creative resolve, players cannot craft and resolve request, builder will not submit request to relavent crafter (e.g. vertical oak wood planks panel, full varient)

### Expected Behavior

Requests be resolvable

### Reproduction Steps

Using the classic minecolonies build style (mostly oak based), build a build hut level 4, build a hospital level 2.

### Logs

https://gist.github.com/SCBionicle/028390bdf3028687cadfd1be333e9069

### Anything else?

If you want to produce the same exact environment I'm using (be advised, you may have to host the mod pack metadata else where due to the rollback), here is a sample docker-compose file without the backup mechanisms

```yaml
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      DIFFICULTY: "NORMAL"
      OPS: "[Insert minecraft name]"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.2.0"
      PACKWIZ_URL: "http://holl-man.com:8888/MinecoloniesLT/pack.toml"
      RCON_PASSWORD: "derp"
      ENABLE_AUTOPAUSE: "TRUE"
      USE_AIKAR_FLAGS: "TRUE"
      MAX_TICK_TIME: -1
      #RCON_CMDS_ON_CONNECT: |-
      #  mc colony requestsystem-reset-all
      INIT_MEMORY: 512M
      MAX_MEMORY: 15G
      TZ: America/Chicago
      EXISTING_OPS_FILE: "SYNCHRONIZE"
      ENABLE_QUERY: "FALSE"
      VIEW_DISTANCE: 4
      STOP_DURATION: 55
      AUTOPAUSE_TIMEOUT_EST: 3660
      #AUTOPAUSE_TIMEOUT_INIT: 10
      ALLOW_FLIGHT: TRUE
      #DEBUG_AUTOPAUSE: true
volumes:
  mcltdata:
  mcltbackup:
```

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
